version: '3.9'
services:
  web:
    build: 
      context: ./web
    container_name: nodejs
    ports:
      - 8080:8080

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - --config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./loki/loki-config.yml:/mnt/config/loki-config.yaml:ro

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes: 
      - ./grafana/provisioning-datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yml
      