scrape_configs:
  - job_name: 'service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'my-service'
          group: 'production'