scrape_configs:
  - job_name: 'service'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'my-service'
          group: 'production'
  - job_name: 'service java'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'java-service'
          group: 'production'